# Generated by Django 3.0.2 on 2020-04-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20200421_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='_entry_text_excerpt',
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.TextField(),
        ),
    ]
