# Generated by Django 3.0.2 on 2020-04-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_delete_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
    ]
