# Generated by Django 3.0.2 on 2020-04-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20200409_1937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
